### ISSUE TITLE
UC001: lagging Domain hovering tooltip 

### ISSUE THREAD

**Issue by emartinezvic** [ELDAELRA/ELRI#43] opened 2018-11-30 09:54 UTC
When hovering over Domain information the transition between one tooltip and the other results in overlapping unreadable information.

**Comment by luismsgomes** [comment] 2019-02-06 18:04
Is this in the resource metadata view or in the metadata editor?
Which browser did you use?
I could not reproduce the error here (using Firefox):
- in the metadata view, no tooltip appears
- in the metadata editor, the tooltips appear but they do not overlap

**Comment by emartinezvic** [comment] 2019-02-06 20:25
This issue refers to the Domain tooltip in the contribute.html template here: [ELRI/metashare/templates/repository/editor/contributions/contribute.html](ELRI/metashare/templates/repository/editor/contributions/contribute.html).

**Comment by tetchegoyhen** [comment] 2019-02-14 08:54
The issue is fixed on the FCUL branch and we will close it once the branch is merged with the MASTER.

**Closed** 2019-02-22 11:44 UTC
Labels: bug
